version: "3.3"
services:
  data-service:
    build:
      context: .
      dockerfile: data/Dockerfile
    image: data-server
    platform: linux/amd64
    ports:
      - "5003:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - APP_NAME=crypto-bot-data
      - MODEL_APP_URL=http://host.docker.internal:5001
      - EXECUTION_APP_URL=http://host.docker.internal:5002
      - PORT=5000
      - LOGGER_LEVEL=INFO
      - CHECKS_INTERVAL=1800
  model-service:
    build:
      context: .
      dockerfile: model/Dockerfile.web
    image: model-server
    platform: linux/amd64
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - APP_NAME=crypto-bot-model
      - PORT=5000
      - LOGGER_LEVEL=DEBUG
  model-worker:
    build:
      context: .
      dockerfile: model/Dockerfile.worker
    image: model-worker
    platform: linux/amd64
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - EXECUTION_APP_URL=http://host.docker.internal:5002
    depends_on:
      - redis
  execution-service:
    build:
      context: .
      dockerfile: execution/Dockerfile
    image: execution-server
    platform: linux/amd64
    ports:
      - "5002:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - APP_NAME=crypto-bot-execution
      - PORT=5000
      - LOGGER_LEVEL=DEBUG
      - SNAPSHOTS_INTERVAL=900
  redis:
    image: redis
  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    image: dashboard-server
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_DATA_API_HOST=http://localhost:5003
      - REACT_APP_EXECUTION_API_HOST=http://localhost:5002
    volumes:
      - ./dashboard:/app
      - /app/node_modules
volumes:
  postgres:
    driver: local